name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Sync dictionary
      run: bin/sync_dictionaries
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.65.0
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      name: Run cargo fmt
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      name: Run cargo build
      with:
        command: build
        args: --verbose
    - uses: actions-rs/cargo@v1
      name: Run cargo test
      with:
        command: test
        args: --verbose
